apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mail-dev
  name: mail-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mail-dev
    spec:
      containers:
        - args:
          #  env:
          #            - name: PGDATA
          #              value: /data/postgres
          #            - name: POSTGRES_DB
          #              value: order-service
          #            - name: POSTGRES_PASSWORD
          #              value: password
          #            - name: POSTGRES_USER
          #              value: ptechie
          image: maildev/maildev
          name: mail-dev
          ports:
            - containerPort: 1080
            - containerPort: 1025
          resources: {}
          volumeMounts:
            - mountPath: /data/mail-dev
              name: mail-dev-claim0
      restartPolicy: Always
      volumes:
        - name: mail-dev-claim0
          persistentVolumeClaim:
            claimName: mail-dev-claim0
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mail-dev
  name: mail-dev
spec:
  ports:
    - name: "1080"
      port: 1080
      targetPort: 1080
    - name: "1025"
      port: 1025
      targetPort: 1025
  selector:
    app: mail-dev
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mail-dev-claim0
  name: mail-dev-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
